name: Test

on:
  workflow_dispatch:

jobs:
  create:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Authenticate to Google Cloud (Direct Access)
        uses: google-github-actions/auth@v1
        with:
          create_credentials_file: true
          workload_identity_provider: "projects/341213114487/locations/global/workloadIdentityPools/actionscheck/providers/actionscheck"


      - name: List GCS buckets
        run: gcloud storage buckets list
