name: Test

on:
  workflow_dispatch:

jobs:
  create:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Authenticate to Google Cloud (Direct Access)
        uses: google-github-actions/auth@v3
        with:
          project_id: '341213114487'
          workload_identity_provider: "projects/341213114487/locations/global/workloadIdentityPools/actionscheck/providers/actionscheck"


      - name: List GCS buckets
        run: gcloud artifacts repositories list --project=341213114487
